platiagro/projects

projects/controllers/experiments.py
projects/controllers/operators.py

It was relying on the order returned by the query. Now, 'order by'
clause enforces to keep the previous positions.

Fix sort operations on fix_position

---

projects/samples.py

If an existing component is_default = 1, and names are equal,
do not create the component from --sample-config.

Avoids duplicates components when --sample-config is set

---

docs/swagger.yaml
projects/controllers/operators.py
projects/models/operators.py
tests/test_experiments.py
tests/test_operators.py
tests/test_templates.py

- Adds a new column 'parameters', type JSON to table 'operators'
- Validates if parameters is a dictionary
(object str->[str|int|float])
- Adds unit tests
- Updates docs

Allows saving parameters values in an operator

---

projects/controllers/components.py
projects/jupyter.py
projects/object_storage.py

PlatIAgro notebooks have experiment_id and operator_id in their
metadata to interact with PlatIAgro SDK functions.
Newly created components were copying the metadata from other
components, which may cause unexpected behavior.
experiment_id and operator_id are now randomized and set during
creation step.

Set experiment_id and operator_id when creating components

---

samples/automl-classifier/Training.ipynb
samples/automl-regressor/Training.ipynb

Refit requires data to be preprocessed, just like automl.fit().
Not doing so causes errors like this:
ValueError: could not convert string to float: '2016-10-08'

Calls pipeline.transform() before automl.refit()

---

samples/feature-tools/Experiment.ipynb
samples/feature-tools/ftools.py

Removed !wget duplicated and put datetime convert to str so that a "ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing" doesn't happen. Also added infer_format... = True.

Fix ftools pd_todatetime by changing datetime type to str.

---

setup.py

Papermill dependecy isn't in setup.py's extras.
It's necessary for tests.

Added Papermill Dependency

---

projects/jupyter.py

- when a runtime error occurred in any cell in the notebook, it was not possible to catch the exact error, since it was defined to catch the first one at any time, and this type of error generates stream outputs

Fix Notebook Logger

---

projects/controllers/tasks.py
projects/jupyter.py
tests/test_tasks.py

Improvement for tasks of tag 'DATASETS': they do not use Jupyter
Notebooks, so there is no need to create/upload .ipynb files for
them.

Allows nullable experiment_notebook

---

projects/config/Deployment.ipynb
samples/automl-classifier/Deployment.ipynb
samples/automl-regressor/Deployment.ipynb
samples/feature-tools/Deployment.ipynb
samples/filter-selection/Deployment.ipynb
samples/grouping-categorical-features/Deployment.ipynb
samples/imputer/Deployment.ipynb
samples/isolation-forest-clustering/Deployment.ipynb
samples/kmeans-clustering/Deployment.ipynb
samples/linear-regression/Deployment.ipynb
samples/logistic-regression/Deployment.ipynb
samples/mlp-classifier/Deployment.ipynb
samples/mlp-regressor/Deployment.ipynb
samples/normalizer/Deployment.ipynb
samples/pre-selection/Deployment.ipynb
samples/random-forest-classifier/Deployment.ipynb
samples/random-forest-regressor/Deployment.ipynb
samples/rfe-selector/Deployment.ipynb
samples/robust-scaler/Deployment.ipynb
samples/simulated-annealing/Deployment.ipynb
samples/svc/Deployment.ipynb
samples/svr/Deployment.ipynb
samples/transformation-graph/Deployment.ipynb
samples/variance-threshold/Deployment.ipynb

When seldon receives a 'binData' or 'strData' it does not pass
'meta' to predict, causing deployments that used these notebooks
to crash.
By using a default value `meta=None` we avoid this bug.

Adds default value='None' to Deployment.ipynb files

---

setup.py

Fix an issue in which autosklearn failed to import a module:
ModuleNotFoundError: No module named 'smac.tae.execute_ta_run'

Sets SMAC >=0.12,<0.13 as testing version

---

.github/workflows/pythonapp.yml
projects/api/compare_results.py
projects/api/experiments.py
projects/api/json_encoder.py
projects/api/main.py
projects/api/operators.py
projects/api/parameters.py
projects/api/projects.py
projects/api/tasks.py
projects/api/templates.py
projects/controllers/compare_results.py
projects/controllers/dependencies.py
projects/controllers/experiments.py
projects/controllers/operators.py
projects/controllers/parameters.py
projects/controllers/projects.py
projects/controllers/tasks.py
projects/controllers/templates.py
projects/controllers/utils.py
projects/jupyter.py
projects/models/__init__.py
projects/models/compare_result.py
projects/models/dependency.py
projects/models/experiment.py
projects/models/operator.py
projects/models/project.py
projects/models/task.py
projects/models/template.py
projects/samples.py
tests/test_tasks.py

This was changed because PEP 8 encourages absolute imports:
See https://www.python.org/dev/peps/pep-0008/ for further details.
Also added a instruction to use absolute imports in code-review tips.

Replaces relative imports by absolute imports

---

projects/samples.py

- set a default image
- if the task does not have the "image" property, look for the environment variable that is created in the cluster manifests, and finally, if this variable does not exist, use the default image

Task Environment Configuration

---

docs/swagger.yaml
projects/controllers/deployments/runs/logs.py
projects/kfp/pipeline.py
projects/kfp/templates.py

- retrives operator task name from `metadata.annotations.tasks`
- update swagger: add status to the Deployment log section

Add Tasks in the metadata.annotations of the Pod Object

---

projects/api/projects.py
projects/kfp/pipeline.py
projects/kfp/templates.py
projects/models/task.py

Uses the new env variable defined in manifests:
TASK_DEFAULT_DEPLOYMENT_IMAGE
Also renames the image for experiments to
TASK_DEFAULT_EXPERIMENT_IMAGE
Usa os nomes definidos no repo manifests:
https://github.com/platiagro/manifests/blob/2cbcb9058968966bda5ef01a1804ff32e26219d5/platiagro/projects/base/deployment.yaml#L41

Sets seldon deployment image using env variable

---

projects/controllers/deployments/runs/runs.py
projects/controllers/experiments/runs/runs.py

Necesssary since persistence-agent has a delay to update the status,
and a bad feedback was provided in web-ui (it seemed nothing changed
in operator' status.

Set status=Pending in operators when a run starts

---

projects/api/deployments/runs/logs.py
projects/controllers/deployments/runs/logs.py
projects/controllers/deployments/runs/runs.py
projects/kfp/pipeline.py
projects/kfp/runs.py
projects/kfp/templates.py
projects/kubernetes/utils.py

Fix logs list when seldon deployment fails
Fix get_latest_run_id …
Don't check workflow manifest name == 'experiment-...', it's
unnecessary and caused get_latest_run_id to fail for deployments.
Uses deployment_id as kfp.experiment name …
Allows to retrieve deployment runs easier that before (when
we had to use deployment.experiment_id).
Calls parse_logs to return structured logs
Hides seldon-container-engine from deployment logs

Fix logs list when seldon deployment fails

---

projects/agent/main.py

When the requested watch operations fail because the historical version
of that resource is not available, clients must handle the case by
recognizing the status code 410 Gone, clearing their local cache,
performing a list operation, and starting the watch from the resourceVersion
returned by that new list operation.

Fix 410 Gone errors in persistence agent

---

README.md
docker-compose.yml
projects/controllers/projects.py
projects/controllers/utils.py
projects/models/deployment.py
projects/models/experiment.py
projects/models/project.py

When the parent is marked for deletion, then a child object will be
marked for deletion also.
This makes the code simpler and shorter.

Replaces manual child deletion by delete cascade

---

projects/controllers/deployments/runs/logs.py
projects/kfp/pipeline.py
projects/kubernetes/argo.py

When a deployment fails (before seldondeployments are created),
no logs were shown.
This commit returns the logs from workflow pods since they are useful
for debugging errors.

Returns workflow logs when seldondeployments don't exist

---

projects/controllers/utils.py
requirements.txt

Adds a new requirement:
filetype==1.0.7 - package to infer file type and MIME type
Infers the MIME type using the lib filetype, and passes it to
seldon deployment using a field in the body:
{..., "meta":{"content-type": "here-the-mime-type"}}
This is useful for tasks that receive a binary body (eg. images, audio),
but also need some metadata about the content (the MIME type).

Sends "content-type" to seldon deployment in .../predictions

---

projects/api/main.py

Our devs have reported that CORS seems not to be working after
the migration to FastAPI.
We find out lots of message at GitHub confirming these issues:
https://github.com/tiangolo/fastapi/issues/1663
This fix creates a route that handles "OPTIONS" requests and
returns the CORS headers:
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: Authorization, Content-Type
All references to CORSMiddleware were removed.

Fix issues regarding CORSMiddleware

---

docs/swagger.yaml
projects/schemas/operator.py

By adding the task name on the operator, we prevent a request
to list all tasks (to find a name of a operator.taskId).
Also updates Swagger UI docs.

Adds taskName to operators response

---

docs/swagger.yaml

API /projects has the attribute "deployments" which wasn't mentioned.

Adds attribute "deployments" to Swagger docs

---

projects/controllers/deployments/deployments.py
projects/controllers/tasks/tasks.py
projects/jupyter.py
projects/kubernetes/notebook.py
projects/schemas/task.py

This feature disabled the link to JupyterLab when containerState
was false. However, we have improved the link to JupyterLab with a
loading screen and disabling the button no longer makes sense.

Removes tasks.containerState occurrences

---

docs/swagger.yaml

This endpoint returns a list of "data URIs" generated by a monitoring
task.

Adds endpoint ../monitorings/:id/figures to Swagger docs

---

projects/controllers/logs/logs.py
tests/test_logs.py

- Fix regex to match only lines that include log level
- Remove timestamps from lines of message body

Fix parsing of logs with multiple lines

---

.github/workflows/ci.yml
projects/api/projects.py
projects/controllers/projects.py
projects/utils.py
tests/test_experiments.py
tests/test_projects.py

Query params with invalid characters, such as whitespaces, are not returning the expected result.
Now format_query_params is using urllib.parse.parse_qsl, this automatically parses the query parameters string to dict and eliminates invalid characters.
Change ilike comparison encoding to verify accents.

Fix format_query_params

---

projects/agent/watchers/workflow.py

Removes logic that set status = 'Unset' for operators that were not
listed. Latest Argo, now lists all nodes, and the ones that did start
run have status = 'Omitted'. We translate 'Omitted' to 'Failed'.

Adapts workflow watcher to latest Argo Workflows responses

---

projects/agent/watchers/workflow.py
projects/controllers/deployments/deployments.py
projects/controllers/operators/operators.py
projects/schemas/operator.py

No longer update updates status of deployment operators. Set the default for these operators to "Setted up".

Set status of deployment operators to Setted up

---

projects/api/deployments/runs/runs.py
projects/api/monitorings/monitorings.py
projects/controllers/deployments/deployments.py
projects/controllers/deployments/runs/runs.py
projects/controllers/monitorings/monitorings.py
tests/test_deployments_runs.py

This is a workaround to allow the user to test the deployment pipeline before deploying manually.

On create_deployment start a new deployment run

---

projects/models/project.py

Thus, the has_deployment is only true when a deployment has been succeeded.

Check for status and url to define if a projects has a deployment.

---

Dockerfile
requirements.txt

kfp was updated and there is no longer a conflict of kubernetes sdk versions.
We can set kubernetes==12.0.1 in requirements.txt and install all libs in
one step (and remove extra pip install from Dockerfile).
Kubernetes SDK 12.0.1 is required in order to read and write bytes when
executing commands on containers. The previous SDK version (10) allowed
only to send/receive str.

Sets kubernetes==12.0.1 in requirements.txt

---

docker-compose.yml
docs/swagger.yaml
projects/api/deployments/deployments.py
projects/api/experiments/experiments.py
projects/controllers/logs/logs.py
projects/kubernetes/utils.py
requirements.txt

Motivação: existem APIs que são utilizadas em formato polling (consulta periódica). Apesar de fácil de implementar, o polling não é a estratégia mais eficiente (trafega dados mesmo quando não há alterações na API).
Criar os endpoints:
/projects/:id/experiments/:id/logs/eventsource
Handler that returns the generated event source that is responsible for returning logs from given deployment's pod. If the deployment is finished, there's no pod online then being unable to create a log stream 
/projects/:id/deployments/:id/:task_name/logs/eventsource
Since we can currently watch only one pod at a time, the handler needs to receive the task name because an experiment may have more than one task and each task generates one pod.

[PROJECTS] API EventSource para logs

---

docker-compose.yml
docs/swagger.yaml
projects/api/deployments/deployments.py
projects/api/experiments/experiments.py
projects/api/experiments/operators/operators.py
projects/controllers/logs/logs.py
projects/controllers/operators/operators.py
projects/kubernetes/utils.py
requirements.txt

Motivação: existem APIs que são utilizadas em formato polling (consulta periódica). Apesar de fácil de implementar, o polling não é a estratégia mais eficiente (trafega dados mesmo quando não há alterações na API).
Iremos criar uma API Eventsource (server side events) que é uma forma mais eficiente, que só trafega dados quando são gerados.
Foram criados os endpoints:
/projects/:id/experiments/:id/operators/eventsource

[PROJECTS] API EventSource para operators

---

docs/swagger.yaml

Uvicorn run as default on port 8000, so I thought that would be a good idea to include it in the swagger instead of just the 8080 port

Including port 8000 in swagger

---

projects/models/comparison.py
projects/models/deployment.py
projects/models/experiment.py
projects/models/operator.py
projects/models/project.py
projects/models/template.py
projects/utils.py
tests/test_projects.py
tests/test_utils.py
tests/util.py

Reprodução:
Implantar um fluxo (com computador no horário de brasília)
Resultado (foto em anexo)
No canto superior o horário local, e no campo “Data de criação”, 3 horas adiantado)
ANÁLISE DE ERRO: 
O backend da plataforma retorna as datas no fuso "UTC", porém usa formatação errada, pois a hora não termina com "Z" ou "+00:00".
DESIGN DE SOLUÇÃO:
Adicionar a informação de timezone ("Z" ou "+00:00") nos atributos updated_at e created_at nas APIs.

Added timezone in the timestamp of projects, experiments and deployments

---

projects/api/tasks/tasks.py
projects/controllers/tasks/tasks.py
projects/kfp/tasks.py
projects/kfp/volume.py
tests/test_tasks.py

JIRA: https://jira.cpqd.com.br/browse/PLATIA-2265
Atualmente a PlatIA utiliza a funcionalidade backgroundTasks como forma de manter a assincronicidade das operações, entretanto, diversos problemas vem ocorrendo nessa metodologia. Dito isto, esse pull request intenta 'terceirizar' a deleção de tarefas para o kubeflow através do kfp e por consequência tirar a sobrecarga de operações do FastAPI.

PLATIA-2265/feature/deletion-as-job
