platiagro/projects

- README.md
- docs/swagger.yaml
- projects/controllers/components.py
- projects/models/component.py
- projects/samples.py
- samples/config.json
- setup.py
- tests/test_components.py
- tests/test_operators.py
- tests/test_parameters.py
- tests/test_samples.py
- Adds column tags to model/table (type is JSON)
- Adds tags to docs
- Updates unit tests
- Adds tags and description to samples config
> Adds tags to components

- samples/automl-classifier/Training.ipynb
- samples/automl-regressor/Training.ipynb
- samples/linear-regression/Training.ipynb
- samples/logistic-regression/Training.ipynb
- samples/mlp-classifier/Training.ipynb
- samples/mlp-regressor/Training.ipynb
- samples/random-forest-classifier/Training.ipynb
- samples/random-forest-regressor/Training.ipynb
- samples/svc/Training.ipynb
- samples/svr/Training.ipynb
load_metadata was renamed to stat_dataset
> Update code to latest SDK definition

- samples/config.json
- samples/imputer/Inference.ipynb
- samples/imputer/Training.ipynb
- samples/quantile-transformer/Inference.ipynb
- samples/quantile-transformer/Training.ipynb
- samples/variance-threshold/Inference.ipynb
- samples/variance-threshold/Training.ipynb
- Imputer: imputing missing values
- Variance Threshold: removes all low-variance features
- Quantile Transformer: transforms the features to follow a uniform
or a normal distribution
> Adds new sample components

- samples/config.json
- samples/robust-scaler/Inference.ipynb
- samples/robust-scaler/Training.ipynb
Scale features using statistics that are robust to outliers.
> Adds Robust Scaler component

- samples/automl-classifier/Training.ipynb
- samples/automl-regressor/Training.ipynb
- samples/imputer/Inference.ipynb
- samples/imputer/Training.ipynb
- samples/linear-regression/Training.ipynb
- samples/logistic-regression/Training.ipynb
- samples/mlp-classifier/Training.ipynb
- samples/mlp-regressor/Training.ipynb
- samples/normalizer/Training.ipynb
- samples/random-forest-classifier/Training.ipynb
- samples/random-forest-regressor/Training.ipynb
- samples/svc/Training.ipynb
- samples/svr/Training.ipynb
Removes all NaN columns, then use replacement for remaining NaNs
> Handled all NaN columns

- samples/automl-classifier/Training.ipynb
- samples/automl-regressor/Training.ipynb
- samples/imputer/Training.ipynb
- samples/linear-regression/Training.ipynb
- samples/logistic-regression/Training.ipynb
- samples/mlp-classifier/Training.ipynb
- samples/mlp-regressor/Training.ipynb
- samples/normalizer/Training.ipynb
- samples/random-forest-classifier/Training.ipynb
- samples/random-forest-regressor/Training.ipynb
- samples/robust-scaler/Training.ipynb
- samples/svc/Training.ipynb
- samples/svr/Training.ipynb
- samples/variance-threshold/Training.ipynb
- Add new cell description for hyperparameters selection
- Add dict of essential parameters among those offered by the class of each model
- Change the class constructor call by passing the dict destruct with the selected hyperparameters as an argument
Task_ID: PLATIA-629
> Add Hyperparameters Selection

- docs/swagger.yaml
- projects/controllers/components.py
- projects/controllers/projects.py
- projects/controllers/templates.py
See: https://en.wikipedia.org/wiki/Natural_sort_order
Improves user experience by providing a more human-readable order.
Example:
Alphabetical sorting:
z11
z2
Natural sorting:
z2
z11
> Sort projects, experiments, and templates in natural sort order

- projects/controllers/operators.py
papermill allows these types and so should we.
> Allows parameters of type list and dict

- projects/controllers/operators.py
> Revert "Allows parameters of type list and dict"

- projects/controllers/operators.py
Papermill allows it, and so should we.
> Allows parameters of type bool

- projects/jupyter.py
Retry 5 times before returning an error.
backoff_factor allows to wait a amount of time before each retry.
> Adds a retry strategy for requests sent to Jupyter

- projects/database.py
Adds pool_recycle as suggested here:
https://docs.sqlalchemy.org/en/13/faq/connections.html#mysql-server-has-gone-away
Also increases pool_size from 5 (default) to 20.
> Attempt to fix MySQL Server has gone away

- samples/feature-tools/Experiment.ipynb
- samples/simulated-annealing/Experiment.ipynb
- samples/simulated-annealing/simulated.py
- samples/transformation-graph/Experiment.ipynb
- samples/transformation-graph/tgraph.py
Deleted notebooks cells that removes "?" values. 
Fix bug by considering DateTime as Categorical to encode.
> Fix bugs of tgraph and simulated classes

- samples/automl-regressor/Experiment.ipynb
- samples/linear-regression/Experiment.ipynb
- samples/mlp-regressor/Experiment.ipynb
- samples/random-forest-regressor/Experiment.ipynb
- samples/svr/Experiment.ipynb
Target label encoder was removed from all regression components
> Removes target label encoder from regression tasks

- samples/config.json
- samples/descriptive-analysis/Experiment.ipynb
Generate descriptive statistics for a given dataset.
> Descriptive Analysis

- samples/logistic-regression/Deployment.ipynb
- samples/logistic-regression/Experiment.ipynb
Example of changes using Logistic Regression component:
- Included new parameter (model_features) that selects only the features that should be used to perform the model.
- Added new cell (Keep selected features to perform the model) that stores in X the features filtered in model_features parameter
- Added save dataset cell that stores in the dataframe the model result (predictions)
- Prediction results were also saved in deployment notebook.
> Add save dataset and filtered features to perform the model

- projects/config/Experiment.ipynb
- samples/automl-classifier/Experiment.ipynb
- samples/automl-regressor/Experiment.ipynb
- samples/descriptive-analysis/Experiment.ipynb
- samples/feature-tools/Experiment.ipynb
- samples/filter-selection/Experiment.ipynb
- samples/imputer/Experiment.ipynb
- samples/isolation-forest-clustering/Experiment.ipynb
- samples/kmeans-clustering/Experiment.ipynb
- samples/linear-regression/Experiment.ipynb
- samples/logistic-regression/Experiment.ipynb
- samples/mlp-classifier/Experiment.ipynb
- samples/mlp-regressor/Experiment.ipynb
- samples/normalizer/Experiment.ipynb
- samples/pre-selection/Experiment.ipynb
- samples/random-forest-classifier/Experiment.ipynb
- samples/random-forest-regressor/Experiment.ipynb
- samples/rfe-selector/Experiment.ipynb
- samples/robust-scaler/Experiment.ipynb
- samples/simulated-annealing/Experiment.ipynb
- samples/svc/Experiment.ipynb
- samples/svr/Experiment.ipynb
- samples/transformation-graph/Experiment.ipynb
- samples/variance-threshold/Experiment.ipynb
- Change `load_dataset` and `save_dataset` to `pandas.DataFrame.read_csv` and `pandas.DataFrame.to_csv`, respectively.
> Change Save and Load Dataset Options

- samples/automl-classifier/Experiment.ipynb
- samples/automl-regressor/Experiment.ipynb
- samples/descriptive-analysis/Experiment.ipynb
- samples/feature-tools/Experiment.ipynb
- samples/filter-selection/Experiment.ipynb
- samples/grouping-categorical-features/Experiment.ipynb
- samples/imputer/Experiment.ipynb
- samples/isolation-forest-clustering/Experiment.ipynb
- samples/kmeans-clustering/Experiment.ipynb
- samples/linear-regression/Experiment.ipynb
- samples/logistic-regression/Experiment.ipynb
- samples/mlp-classifier/Experiment.ipynb
- samples/mlp-regressor/Experiment.ipynb
- samples/normalizer/Experiment.ipynb
- samples/pre-selection/Experiment.ipynb
- samples/random-forest-classifier/Experiment.ipynb
- samples/random-forest-regressor/Experiment.ipynb
- samples/rfe-selector/Experiment.ipynb
- samples/robust-scaler/Experiment.ipynb
- samples/simulated-annealing/Experiment.ipynb
- samples/svc/Experiment.ipynb
- samples/svr/Experiment.ipynb
- samples/transformation-graph/Experiment.ipynb
- samples/variance-threshold/Experiment.ipynb
- add csv extension for all default dataset values
> Add Extension to Dataset Parameter

- samples/rfe-selector/Experiment.ipynb
It had a double close "}" at RFE component.
> Fix double close "}" at target param.

- samples/automl-classifier/Deployment.ipynb
- samples/automl-classifier/Experiment.ipynb
- samples/automl-regressor/Deployment.ipynb
- samples/automl-regressor/Experiment.ipynb
- samples/linear-regression/Deployment.ipynb
- samples/linear-regression/Experiment.ipynb
- samples/logistic-regression/Deployment.ipynb
- samples/logistic-regression/Experiment.ipynb
- samples/mlp-classifier/Deployment.ipynb
- samples/mlp-classifier/Experiment.ipynb
- samples/mlp-regressor/Deployment.ipynb
- samples/mlp-regressor/Experiment.ipynb
- samples/random-forest-classifier/Deployment.ipynb
- samples/random-forest-classifier/Experiment.ipynb
- samples/random-forest-regressor/Deployment.ipynb
- samples/random-forest-regressor/Experiment.ipynb
- samples/svc/Deployment.ipynb
- samples/svc/Experiment.ipynb
- samples/svr/Deployment.ipynb
- samples/svr/Experiment.ipynb
Fix the following error - IndexError: boolean index did not match indexed array along dimension 0; dimension is 14 but corresponding boolean dimension is 13.
> The variable used to obtain final columns was wrong.

- projects/controllers/projects.py
- projects/controllers/tasks.py
- tests/test_tasks.py
- whenever the database was down, status 400 (Bad Request) was returned instead of 500 (Internal Server Error)
> MySQL/ Return Internal Error Response

- projects/controllers/tasks.py
> Adds new VALID_TAGS to tasks

- docs/swagger.yaml
- projects/controllers/deployments/runs/runs.py
- projects/controllers/experiments/runs/runs.py
- projects/kfp/pipeline.py
- projects/kfp/runs.py
- projects/kfp/templates.py
- projects/kubernetes/seldon.py
- projects/models/project.py
- tests/test_experiments.py
- tests/test_projects.py
- add `hasExperiment`, `hasPreDeployment` and `hasDeployment` properties on GET /projects/:id endpoint
- hasExperiment: true if experiments.length > 0
- hasPreDeployment: true if deployments.length > 0
- hasDeployment: true if Seldondeployment exists
- update swagger doc
> Project Tags

- projects/api/deployments/deployments.py
- projects/api/deployments/operators/__init__.py
- projects/api/deployments/operators/operators.py
- projects/api/experiments/runs/datasets.py
- projects/controllers/deployments/deployments.py
- projects/controllers/deployments/runs/runs.py
- projects/controllers/experiments/experiments.py
- projects/controllers/experiments/runs/datasets.py
- projects/controllers/experiments/runs/runs.py
- projects/controllers/operators/operators.py
- projects/controllers/operators/parameters.py
Adds the header 'Content-Disposition' to Streaming response.
> Fix dataset download

- projects/controllers/tasks/tasks.py
- projects/kubernetes/notebook.py
- create a new task in one thread and use asyncio to schedule new task executions to set notebook metadata
> Handle Task Creation

- projects/kfp/runs.py
Returns the appropriate operator status: 'Unset' when a node
is added after an experiment was run.
Continues to return 'Pending' when the experiment is running.
> Fix: operator status 'Pending' for added after a run

- .github/workflows/pythonapp.yml
- Dockerfile.persistenceagent
- projects/agent/main.py
- projects/controllers/deployments/runs/logs.py
- projects/controllers/operators/operators.py
- projects/controllers/operators/parameters.py
- projects/controllers/utils.py
- projects/kubernetes/seldon.py
- projects/models/operator.py
- projects/utils.py
Watches workflow events and updates operators' statuses.
> Adds a persistence agent to watch for workflow events

- projects/api/deployments/responses.py
- projects/api/main.py
- projects/controllers/__init__.py
- projects/controllers/deployments/responses.py
- projects/kfp/pipeline.py
- projects/kfp/templates.py
- projects/models/__init__.py
- projects/models/response.py
- tests/test_responses.py
Removes logger from graph template and appends once to the final step.
> Adjusts deployment to log only the last step response

- docs/swagger.yaml
@miguelfferraz eu tirei esse SeldonStatus porque não lembro dele... você sabe quando ele é retornado?
> Adds Swagger UI docs for deployment responses

- projects/controllers/deployments/runs/runs.py
- projects/controllers/experiments/runs/runs.py
Returns "The specified **run** does not exist".
> Fix misleading error messages in run controller

- projects/api/deployments/runs/runs.py
- projects/api/monitorings.py
- projects/controllers/deployments/responses.py
- projects/controllers/deployments/runs/runs.py
- projects/controllers/monitorings.py
- projects/controllers/tasks/tasks.py
- projects/kfp/monitorings.py
- projects/kfp/templates.py
- projects/kubernetes/notebook.py
- projects/schemas/monitoring.py
- Create and update ConfigMap for monitoring tasks.
- Create a broker for every deployment that has a monitoring task.
- Create a KNative Service and Trigger for each monitoring task during the deployment run.
> Deploy KNative service for monitoring tasks

- projects/agent/main.py
- projects/controllers/experiments/runs/runs.py
- projects/schemas/operator.py
- Clear status_message when start a run.
- Fetch status_message of operators.
> Feature - Fetch status_message from operator

- docs/swagger.yaml
- projects/models/monitoring.py
- projects/schemas/monitoring.py
- tests/test_monitorings.py
- Add task details to monitorings response.
- Update Swagger docs.
- Change monitoring table name to match project pattern (plural).
> Add task to monitorings response

- projects/controllers/tasks/tasks.py
- projects/kubernetes/notebook.py
- get_file_from_pod() are receiving just the experiment notebook file name, this changes fix it to use the correct notebook path.
> Fix - Use the correct notebook path at ConfigMap creation

- projects/kfp/templates.py
Makes GPU devices visible for deployments.
> Adds NVIDIA_VISIBLE_DEVICES=all env variable to seldondeployments

- projects/models/deployment.py
- projects/models/experiment.py
> Adds model relationships to Responses and Comparisons

- projects/api/deployments/deployments.py
- projects/controllers/deployments/deployments.py
- projects/kfp/monitorings.py
- Undeploy monitorings resources (service and trigger) when delete a deployment.
> Fix - Delete deployment monitorings

- projects/schemas/deployment.py
- tests/test_deployments.py
- tests/test_deployments_runs.py
- tests/test_logs.py
- tests/test_monitorings.py
- tests/test_predictions.py
- tests/test_projects.py
- tests/test_responses.py
- tests/test_templates.py
> Fix Deployment.deployed_at type

- projects/kfp/pipeline.py
Better form of handling access keys/secret keys.
Also sets MINIO_ENDPOINT which will be useful to migrate from
minio-service.kubeflow to minio.platiagro.
> Replaces plain env vars by valueFrom secrets

- docs/swagger.yaml
- projects/api/templates.py
- projects/controllers/templates.py
- tests/test_projects.py
- tests/test_templates.py
- Adds unittests
- Updates Swagger docs
> Adds a new endpoint to delete multiple templates

- .github/workflows/ci.yml
- .github/workflows/pythonapp.yml
- docs/swagger.yaml
- projects/api/experiments/runs/results.py
- projects/api/main.py
- projects/controllers/__init__.py
- projects/controllers/experiments/runs/results.py
- projects/controllers/tasks/tasks.py
- projects/object_storage.py
- tests/test_results.py
New endpoints to download experiment results in a zipped file.
Add Swagger docs for experiment results API.
Add unittests to experiment results API.
Runs only test_results.py while we are testing it.
> Adds a new API to download experiment results

- projects/kfp/templates.py
> Sets MinIO key and secret as env variables for deployments

- projects/config/Deployment.ipynb
This method is recommended by seldon core:
https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load
And should be used instead of __init__ for model initialization.
> Adds a .load() method to sample Deployment.ipynb

- projects/api/deployments/deployments.py
- projects/controllers/deployments/deployments.py
- projects/controllers/deployments/runs/runs.py
Check if deployment has at least one operator that is not a data source before start deployment run.
> Check if deployment has at least one operator that is not a data source

- projects/object_storage.py
- requirements.txt
- tests/test_datasets.py
- tests/test_predictions.py
- tests/test_results.py
- tests/test_tasks.py
> WIP: KFP-to-1.6.6

- projects/kubernetes/utils.py
> Adds 'OutOfpods' to IGNORABLE_STATUSES_REASONS

- projects/controllers/tasks/tasks.py
- tests/test_tasks.py
Fixing copies of tasks, before copying task with name of "Tarefa em branco".
> Correcting copies of tasks.

- projects.code-workspace
This file:
- provides a list of recommended extensions
- enforces autoformat using black
- defines a run/debug config for FastAPI
> Adds a VSCode workspace file

- projects/api/tasks/tasks.py
- projects/controllers/tasks/tasks.py
- tests/test_tasks.py
- tests/test_utils.py
Havia um código com bug vindo de uma tentativa de implementação em list_task no controller de task, foi feito apenas uma alteração pra forma funcionante das funções handle_list_task em API e da função list_task em controller. A alteração foi simplesmente copiar da forma que já funcionava antes. @dfvneto @alanmsant2
> PLATIA-2338/fix/screen-of-tasks-bug

- projects/controllers/comparisons.py
- projects/controllers/deployments/deployments.py
- projects/controllers/experiments/experiments.py
- projects/controllers/operators/operators.py
- projects/controllers/projects.py
- projects/controllers/templates.py
- projects/models/comparison.py
- projects/models/deployment.py
- projects/models/experiment.py
- projects/models/operator.py
- projects/models/project.py
- projects/models/template.py
Correção na implantação do timezone no timestamp.
> Horário da implantação do fluxo incorreto - PLATIA 2250

- projects/controllers/tasks/tasks.py
- projects/models/task.py
> added timezone to tasks platia 2465

- projects/controllers/predictions.py
- projects/controllers/tasks/tasks.py
- projects/schemas/project.py
- tests/test_experiments.py
- tests/test_predictions.py
- tests/test_projects.py
Add exception handling for the following exception
> add exception handling
